FROM nginx:alpine

CMD npm install
CMD gulp
ADD assets /usr/share/nginx/html/assets
COPY index.html /usr/share/nginx/html
ADD stubs /usr/share/nginx/html/stubs
COPY default.conf.template /etc/nginx/conf.d/default.conf.template

EXPOSE $PORT
CMD bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
