name: Build and push to static branch

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: dist

  push-static:
    name: 'Push to static branch'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Push to static branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: 'static'
        run: npm run push-static

  update-bleeding-edge:
    name: 'Update bleeding-edge release'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create release package
        run: zip -r dist.zip dist

      - name: Update bleeding-edge release
        uses: WebFreak001/deploy-nightly@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/172897360/assets{?name,label}
          release_id: 172897360
          asset_path: dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
          max_releases: 1

      - name: Update the bleeding-edge tag
        run: |
          git tag -f bleeding-edge
          git push origin bleeding-edge --force
