name: Build and push to static branches

on:
  push:
    branches:
      - master

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          MATRIX='[{"branch":"gh-pages","script":"./bin/build-for-gh-pages.sh"},{"branch":"static","script":"./bin/build-static-site.sh"}]'
          echo $MATRIX
          echo "::set-output name=matrix::$MATRIX"

  build-and-push-static-branches:
    name: "Build ${{ matrix.branch }} branch"
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson( needs.build-matrix.outputs.matrix ) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |
          npm install
          sh ${{ matrix.script }}
      - name: Push to ${{ matrix.branch }} branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: ${{ matrix.branch }}
        run: sh bin/push-build-to-branch.sh
